//Query the names of all the Japanese cities in the CITY table. The COUNTRYCODE for Japan is JPN.

//MYSQL 
SELECT NAME FROM CITY
WHERE COUNTRYCODE='JPN'

//MSSQL
SELECT NAME FROM CITY
WHERE COUNTRYCODE='JPN'

//MONGODB
db.CITY.find({COUNTRYCODE:'JPN'},{NAME:1,_id:0});

//POSTGRESQL
SELECT NAME FROM CITY 
WHERE COUNTRYCODE='JPN'

